### ISSUE TITLE
Board support for XVF3600 Eval Kit

### ISSUE THREAD

**Issue by mbanth** [xmos/fwk_rtos#1]
**Describe the feature**
We will develop [a proposed product](https://xmosjira.atlassian.net/wiki/spaces/VP/pages/3393224707/Hark+-+HiRes+Conferencing) using the [XK-XVF3600-EVK board](https://xmosjira.atlassian.net/wiki/spaces/BOAR/pages/3097788435/JGB0084).  Please provide FreeRTOS board support for this board.

**Will this change any current APIs? How?**
No (as far as I know).

**Who will benefit with this feature?**
XMOS and partner developers initially, customers of the product eventually.

**Any Other info**
Linked information visible only within XMOS.

**Comment by xmos-jmccarthy** [comment]
@mbanth Are the Specifications list on the JGB0084 the only peripheral IO required?

**Comment by mbanth** [comment]
@xmos-jmccarthy, the specification list at [XK-XVF3600-EVK board](https://xmosjira.atlassian.net/wiki/spaces/BOAR/pages/3097788435/JGB0084) is incomplete.  I suspect that it lists the deltas compared to some other board design that @XMOS-JoeG used as a starting point for this one.  The Port Map spreadsheet on the same page provides further information about the peripheral IO.  However, even it does not make crystal clear that this board supports both I2s and USB IO depending on the firmware in use.

**Comment by mbanth** [comment]
I have requested that @tomblackie-xmos send two or three [XK-XVF3600-EVK boards](https://xmosjira.atlassian.net/wiki/spaces/BOAR/pages/3097788435/JGB0084) to the NH office.

**Comment by keithm-xmos** [comment]
Closing.  Will re-open if needed.
