### ISSUE TITLE
UART RTOS Driver

### ISSUE THREAD

**Issue by ed-xmos** [xmos/fwk_rtos#15]
Rx and Tx drivers
Tests for RTOS drivers
Basic documentation

See also xmos/fwk_io#7 for the underlying HIL driver
and
xmos/fwk_io#8 for enhancements following initial drop

**Comment by ed-xmos** [comment]
See https://github.com/xmos/fwk_rtos/pull/27

**Comment by keithm-xmos** [comment]
Closing as this is mostly done.
