### ISSUE TITLE
Investigate issue with updating mbedtls

### ISSUE THREAD

**Issue by jcarrier-xmos** [xmos/fwk_rtos#160]
Investigate the issue with updating to mbedtls 2.28.3 from 2.16.6 (on commit 0abb411350).
This commit has been reverted due to an issue observed in XCORE IoT commit b3bb4cdca5.

At startup the application appears normal while it waits to connect to the specified MQTT broker.

For example:

```
Tile[0]:
       Minimum heap free: 82720
       Current heap free: 119032
Tile[1]:
       Minimum heap free: 99392
       Current heap free: 99448
MQTT Connected
NTP time: 27/4/2023 18:12:42
MQTT Subscribed
Tile[0]:
       Minimum heap free: 61976
       Current heap free: 62360
Tile[1]:
       Minimum heap free: 99392
       Current heap free: 99448
```

After connecting to the MQTT broker/server, the device encounters an exception about a minute or so after this event. It has been observed that publishing to the device's subscribed topic, causes it to hit this exception immediately.

```
Tile[0]:
       Minimum heap free: 61176
       Current heap free: 62360
Tile[1]:
       Minimum heap free: 99392
       Current heap free: 99448
xrun: Program received signal ET_LOAD_STORE, Memory access exception.
     [Switching to tile[0] core[3]]
     0x000b5904 in rtos_locks ()
```

**Comment by xmos-jmccarthy** [comment]
Closed in edb991dd20152861805ecf67335a1cbc3d484dd8
