### ISSUE TITLE
SWMEM driver does not compile without first including xs1.h

### ISSUE THREAD

**Issue by ACascarino** [xmos/fwk_rtos#200]
**System information**
 - OS: All
 - xcore board All
 -  - fwk_rtos version tag or commit SHA: develop

**Describe the current behavior**
When including rtos::freertos as a link library for an application, one driver that is built is rtos_swmem.c
This file includes xcore/swmem_* libraries, which seem to assume that xs1.h has been included.
The build fails because this is not the case.

**Describe the expected behavior**
The build should not fail.

**Standalone code to reproduce the issue**
A minimal reproduceable RTOS project is enough to cause this error.

**Other info or logs** 
This is either a fwk_rtos problem or a Tools problem - should xcore/swmem_* libraries include xs1.h if not already included? Or should the RTOS driver include it? Either way, I don't think the user should be expected to.

**Comment by mbanth** [comment]
Tracked in [Jira issue AP-94](https://xmosjira.atlassian.net/browse/AP-94).
