### ISSUE TITLE
I2S Slave Driver Silent Failure

### ISSUE THREAD

**Issue by xmos-jmccarthy** [xmos/fwk_rtos#36]
**Describe the current behavior**
The I2S slave driver does not support RPC.  Currently, there are no compile nor runtime errors (other than your expected signal not making it to hardware) to alert users.

**Describe the expected behavior**
If the I2S driver is configured for slave mode, error when trying to set up RPC.

**Standalone code to reproduce the issue**
NA

**Other info or logs** 
NA

**Comment by mbanth** [comment]
This issue is now tracked in Jira [AP-157](https://xmosjira.atlassian.net/browse/AP-157).
