### ISSUE TITLE
Linker generates warnings when RTOS NUM_CORES=1

### ISSUE THREAD

**Issue by ed-xmos** [xmos/fwk_rtos#48]
Tools 15.1.4, not sure which RTOS version as there is no changelog, but it's commit https://github.com/xmos/fwk_rtos/commit/2d2da3407e765b4d5e3dd0acae93816b92194483, which is the head of develop.

Note the below are only warnings so not critical, but may reduce confidence in the software package when the user see them.

rtos_osal_thread_port.c: Warning: Undefined reference to 'vTaskCoreAffinityGet'
rtos_osal_thread_port.c: Warning: Undefined reference to 'vTaskCoreAffinitySet'

Talking to @xmos-jmccarthy he agrees the they might need to have empty definitions added to remove the warning since core affinity makes no sense in the 1 core case

**Comment by mbanth** [comment]
This issue is now tracked in Jira [AP-138](https://xmosjira.atlassian.net/browse/AP-138).
