### ISSUE TITLE
Add RTOS support for xscope_host_data

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/fwk_rtos#5]
This would allow support for xscope-based connections from the host - including xscope file io.

**Comment by xmos-jmccarthy** [comment]
No generic xscope_host_data support solution is planned to be added to fwk_rtos, as it is application specific.

The ability to add xscope host connections is now supported at the SDK level, and was tested with xscope_fileio use in an FreeRTOS application.

https://github.com/xmos/fwk_core/commit/0f78ed836ec76d736cd6973d6f8e021ab8f1e620
