### ISSUE TITLE
Fatfs host build won't work with cmake --install

### ISSUE THREAD

**Issue by uvvpavel** [xmos/fwk_rtos#70]
When working on sw_xvf3800 host build and using cmake --install it fails cause https://github.com/xmos/fwk_rtos/blob/develop/modules/sw_services/fatfs/host/CMakeLists.txt#L16 tries to access /opt which can only be done with sudo.

**Comment by keithm-xmos** [comment]
The host applications need to be installed with sudo as documented here:  https://www.xmos.ai/documentation/XM-014660-PC-2/html/doc/quick_start/installation.html#sdk-installation
